apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::918105338854:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LEYHF5WUNQIW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::918105338854:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T10:48:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1616"
  uid: b9437aa3-4bbb-4c94-ac4a-1baa12a655e1
